import AppKit

@MainActor final class ClipboardPlugin {
    let panel: ClipboardPanel
    private let host: DuckpadHost
    private let engine: ClipboardEngine
    private let pasteboard: NSPasteboard
    private var changeCount: Int
    private var expiration = Date()
    private var active = true
    private var presentationGeneration: UInt64 = 0
    private var monitor: Task<Void, Never>?
    private var task: Task<Void, Never>?
    private struct Event { let kind: String; let payload: String; let query: String; let token: UInt64; let generation: UInt64; let image: Data?; let imageFile: URL? }
    private var queue: [Event] = []
    private var rows: [ClipboardRow] = []
    private var retention = 7
    private let resourceDirectory: URL
    init(host: DuckpadHost, config: [String: String]) {
        self.host = host
        resourceDirectory = URL(fileURLWithPath: config["resourceDirectory"] ?? "")
        L10n.catalog = .init(language: config["language"] ?? "en", directory: resourceDirectory)
        panel = ClipboardPanel()
        engine = ClipboardEngine(directory: URL(fileURLWithPath: config["storageDirectory"] ?? ""))
        pasteboard = config["testPasteboard"].map { NSPasteboard(name: .init($0)) } ?? .general
        changeCount = pasteboard.changeCount
        panel.refreshLocalization()
        panel.onEvent = { [weak self] kind, payload, query in self?.send(kind, payload: payload, query: query) }
        panel.onClose = { [weak self] in self?.presentationGeneration &+= 1; self?.host.closePanel() }
        send("query", payload: "", query: "")
        monitor = Task { @MainActor [weak self] in
            while !Task.isCancelled {
                do { try await Task.sleep(for: .milliseconds(500)) } catch { return }
                guard let self, self.active else { return }
                self.poll()
            }
        }
    }
    func show() -> NSView { presentationGeneration &+= 1; panel.prepareForDisplay(); send("query", payload: "", query: panel.query); return panel }
    func setLanguage(_ language: String) {
        L10n.catalog = .init(language: language, directory: resourceDirectory)
        panel.refreshLocalization()
    }
    func stop() {
        active = false; monitor?.cancel(); monitor = nil; task?.cancel(); task = nil; queue.removeAll()
        panel.onEvent = nil; panel.onClose = nil
    }
    private func poll() {
        if Date().timeIntervalSince(expiration) >= 60 {
            expiration = Date(); send("query", payload: "", query: panel.query)
        }
        guard changeCount != pasteboard.changeCount else { return }
        changeCount = pasteboard.changeCount
        let excluded = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]
        guard !excluded.contains(where: { pasteboard.types?.contains(.init($0)) == true }) else { return }
        // Read NSURL objects through AppKit so sandbox pasteboard grants travel
        // with the URLs. Never infer a file from an ordinary text/filename item.
        let files = (pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL] ?? [])
            .filter { ["png", "jpg", "jpeg", "tif", "tiff"].contains($0.pathExtension.lowercased()) }
        if !files.isEmpty {
            for file in files.prefix(200) { send("capture-image", payload: "", query: panel.query, imageFile: file) }
            return
        }
        for type in [NSPasteboard.PasteboardType.png, .tiff, .init("public.jpeg")] {
            if let data = pasteboard.data(forType: type), data.count <= ClipboardImageStore.maximumBytes {
                send("capture-image", payload: "", query: panel.query, image: data)
                return
            }
        }
        guard let text = pasteboard.string(forType: .string), !text.isEmpty,
              text.utf8.count <= ExtensionListProtocol.maximumPayloadBytes else { return }
        send("capture", payload: text, query: panel.query)
    }

    private func send(_ kind: String, payload: String, query: String, image: Data? = nil, imageFile: URL? = nil) {
        guard active else { return }
        let isPaste = kind == "select" || kind == "select-next"
        let isImage = rows.first { $0.id == payload }?.image != nil
        let token = isPaste && !isImage ? host.prepareInsert() : 0
        if isPaste && !isImage && token == 0 { panel.finishPaste(id: payload, query: query, advance: false, succeeded: false); return }
        if imageFile == nil, ["capture", "capture-image", "query", "preview"].contains(kind) {
            queue.removeAll { $0.kind == kind && $0.imageFile == nil }
        }
        queue.append(Event(kind: kind, payload: payload, query: query, token: token, generation: presentationGeneration, image: image, imageFile: imageFile))
        guard task == nil else { return }
        task = Task { @MainActor [weak self] in
            guard let self else { return }
            defer { self.task = nil }
            while self.active, !self.queue.isEmpty, !Task.isCancelled {
                let event = self.queue.removeFirst()
                do {
                    let paste = event.kind == "select" || event.kind == "select-next"
                    let result = try await self.engine.process(event: paste ? "select" : event.kind, payload: event.payload, query: event.query, image: event.image, imageFile: event.imageFile)
                    guard self.active, !Task.isCancelled else { return }
                    if event.kind == "preview" {
                        self.panel.renderPreview(result.selectedText, imageData: result.imageData, id: event.payload, query: event.query)
                    } else {
                        self.rows = result.rows; self.retention = result.retentionDays
                        self.panel.render(result.rows, retentionDays: result.retentionDays, error: nil, thumbnails: result.thumbnails)
                    }
                    if paste, event.generation == self.presentationGeneration,
                       self.panel.window != nil, !self.panel.isHiddenOrHasHiddenAncestor {
                        let success: Bool
                        if result.selectedImage != nil, let data = result.imageData {
                            self.pasteboard.clearContents()
                            success = self.pasteboard.setData(data, forType: .png)
                        } else {
                            success = !result.selectedText.isEmpty && self.host.insert(result.selectedText, token: event.token)
                        }
                        if success { self.changeCount = self.pasteboard.changeCount }
                        self.panel.finishPaste(id: event.payload, query: event.query, advance: event.kind == "select-next", succeeded: success, copiedImage: result.selectedImage != nil)
                    }
                } catch {
                    guard self.active, !Task.isCancelled else { return }
                    self.panel.render(self.rows, retentionDays: self.retention, error: L10n.catalog.text("Plugin request failed: %1$@", arguments: [String(describing: error)]))
                }
            }
        }
    }
}
